### ISSUE TITLE
modoboa.lib.parameters.NotDefined: Application 'postfix_autoreply' and/or parameter 'AUTOREPLIES_TIMEOUT' not defined

### ISSUE THREAD

**Issue by harobed** [modoboa/modoboa-postfix-autoreply#5]
```
(vtenv)vagrant@modoboa:~/modoboa_instancepython manage.py autoreply sklein@example.com sklein2@example.com
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/vtenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/vtenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/vtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/vtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/modoboa-postfix-autoreply/modoboa_postfix_autoreply/management/commands/autoreply.py", line 72, in handle
    send_autoreply(sender, mbox, armessage)
  File "/home/vagrant/modoboa-postfix-autoreply/modoboa_postfix_autoreply/management/commands/autoreply.py", line 31, in send_autoreply
    app="postfix_autoreply")
  File "/home/vagrant/modoboa/modoboa/lib/parameters.py", line 267, in get_admin
    __is_defined(app, "A", name)
  File "/home/vagrant/modoboa/modoboa/lib/parameters.py", line 215, in __is_defined
    raise NotDefined(app, name)
modoboa.lib.parameters.NotDefined: Application 'postfix_autoreply' and/or parameter 'AUTOREPLIES_TIMEOUT' not defined
```

**Comment by harobed** [comment]
In source code, I see only this "autoreplies_timeout" reference : 

```
modoboa-postfix-autoreply/modoboa_postfix_autoreply/management/commands/autoreply.py|30 col 41| timeout = parameters.get_admin("AUTOREPLIES_TIMEOUT",
modoboa-postfix-autoreply/modoboa_postfix_autoreply/app_settings.py|17 col 5| autoreplies_timeout = forms.IntegerField(
```

**Comment by harobed** [comment]
Parameter is present in database : 

```
mysql> select * from lib_parameter;
...
| 24 | modoboa_postfix_autoreply.AUTOREPLIES_TIMEOUT    | 86400
```
